### PR TITLE
Made some changes to the paper text

### PR DESCRIPTION
**Pull request by zachary-foster**
i noticed its hard to see what changes were made since each paragraph is on one line. I suggest doing one sentence per line. They will still form a paragraph in the output, but it is easier to see changes and exta long sentences stand out.

Associated with issue #17

### CODE REVIEW

**Comment by emdelponte** [comment]
@zachary-foster I think I see what you mean. It is the wysiwyg in me! :)  need to learn about this review request. Should I do/hit something?

**Comment by zachary-foster** [comment]
> It is the wysiwyg in me! 

Haha, no problem, the one-sentence-per-line thing is just my own preference. I am not sure I have ever heard any other people recommending it.

>  Should I do/hit something?

I am actually not sure how to indicated that you have reviewed it; I think its a relatively new feature. To apply the changes, you click "Merge pull request".

**Review by emdelponte — COMMENTED** [review]
This looks fine

**Review by adamhsparks — COMMENTED** [review]
Thanks @zachary-foster

**Pull request merged**
